-- DISTINCT 
SELECT DISTINCT FUNCIONARIO.Salario
FROM FUNCIONARIO;
GO

-- WHERE
SELECT *
FROM FUNCIONARIO
WHERE Pnome = 'João';

SELECT *
FROM FUNCIONARIO
WHERE Salario = 25000;
GO

-- AND
SELECT *
FROM FUNCIONARIO
WHERE Sexo = 'M' 
    AND Salario >= 30000;
GO

-- OR
SELECT *
FROM FUNCIONARIO
WHERE Endereco LIKE '%São Paulo%' 
    OR Endereco LIKE '%Curitiba%';
GO

-- NOT
SELECT *
FROM FUNCIONARIO
WHERE NOT Endereco LIKE '%SP' -- LIKE NOT
GO

-- ORDER BY ASC/DESC
SELECT *
FROM FUNCIONARIO
ORDER BY Pnome ASC; -- CRESCENTE

SELECT *
FROM FUNCIONARIO
ORDER BY Salario DESC; -- DECRESCENTE
GO

-- IS NULL / IS NOT NULL
SELECT *
FROM FUNCIONARIO
WHERE Cpf_supervisor IS NULL;

SELECT *
FROM FUNCIONARIO
WHERE Cpf_supervisor IS NOT NULL;
GO

-- SELECT TOP
SELECT TOP 3 *
FROM FUNCIONARIO
WHERE Cpf_supervisor IS NOT NULL
ORDER BY Salario DESC 
GO

-- MIN() / MAX()
-- CONSULTA ANINHADA
SELECT *
FROM FUNCIONARIO
WHERE Salario = (SELECT MIN(Salario) 
                    from FUNCIONARIO);
GO

DECLARE @Salario_Min DECIMAL(10,2);

SELECT @Salario_Min = MIN(Salario)
from FUNCIONARIO;

SELECT *
FROM FUNCIONARIO
WHERE Salario = @Salario_Min
GO

-- COUNT
SELECT COUNT(*) AS 'TOTAL FUNCIONARIOS'
FROM FUNCIONARIO;


SELECT 
    (SELECT COUNT(*) FROM FUNCIONARIO) +
    (SELECT COUNT(*) FROM DEPENDENTE)
    AS 'TOTAL PESSOAS'
GO

-- AVG
SELECT AVG(Salario)
from FUNCIONARIO
GO

-- SUM
SELECT SUM(Salario)
FROM FUNCIONARIO
GO

SELECT
    (SELECT MAX(Salario) FROM FUNCIONARIO) -
    (SELECT AVG(Salario) from FUNCIONARIO)
    AS 'DESVIO ACIMA DA MÉDIA'
GO

-- LIKE
DECLARE @AnoNascimento Date

SET @AnoNascimento = (SELECT Datanasc 
                        FROM FUNCIONARIO 
                        WHERE Pnome = 'Joice')

PRINT YEAR(@AnoNascimento)

SELECT *
FROM FUNCIONARIO
WHERE YEAR(Datanasc) LIKE '__72';
GO

-- IN
SELECT *
FROM FUNCIONARIO
WHERE Salario IN (25000,30000);
GO

SELECT F.Cpf
FROM FUNCIONARIO as F
WHERE F.Pnome = 'Fernando';

SELECT TE.HORAS,TE.Pnr
FROM TRABALHA_EM AS TE
WHERE TE.Fcpf = (SELECT F.Cpf
                    FROM FUNCIONARIO as F
                    WHERE F.Pnome = 'Fernando');

SELECT F.*
FROM FUNCIONARIO AS F, TRABALHA_EM AS TE
WHERE F.Cpf = TE.Fcpf;

SELECT *
FROM FUNCIONARIO AS F
JOIN TRABALHA_EM AS TE ON TE.Fcpf = F.Cpf
WHERE TE.Pnr IN (SELECT Pnr
                    FROM TRABALHA_EM    
                    WHERE Fcpf = '33344555587')
AND TE.Horas IN (SELECT Horas
                    FROM TRABALHA_EM    
                    WHERE Fcpf = '33344555587')
AND NOT F.Pnome = 'Fernando';