USE EMPRESA;

SELECT * FROM FUNCIONARIO;
SELECT * FROM PROJETO;
SELECT * FROM DEPARTAMENTO;

SELECT F.Pnome, F.Unome, F.Endereco
FROM FUNCIONARIO AS F
INNER JOIN DEPARTAMENTO AS D
on F.Dnr = D.Dnumero
WHERE D.Dnome = 'Pesquisa';

SELECT f.Pnome,f.Unome
FROM FUNCIONARIO AS F
INNER JOIN TRABALHA_EM AS TE ON TE.Fcpf = F.Cpf
INNER JOIN PROJETO AS P ON TE.Pnr = P.Projnumero
WHERE P.Projnome = 'ProdutoX';

SELECT P.Projnumero, P.Projnome,D.Dnome, D.Dnumero, F.Unome, f.Datanasc
FROM FUNCIONARIO AS F
INNER JOIN DEPARTAMENTO AS D ON D.Cpf_gerente = F.Cpf
INNER JOIN PROJETO AS P ON P.Dnum = D.Dnumero
INNER JOIN LOCALIZACAO_DEP AS LD ON LD.Dnumero = D.Dnumero
WHERE LD.Dlocal = 'Mauá';