SELECT *
FROM FUNCIONARIO AS F
WHERE F.Cpf_supervisor IS NULL;

SELECT F.Pnome AS 'Funcionario_Nome',G.Pnome 'Gerente_Nome'
FROM FUNCIONARIO AS F
left JOIN FUNCIONARIO AS G ON F.Cpf_supervisor = G.Cpf;

SELECT *
FROM DEPARTAMENTO AS D
LEFT JOIN FUNCIONARIO AS F ON F.Dnr = D.Dnumero
WHERE F.Cpf IS NULL;

SELECT F.Pnome 
FROM DEPENDENTE AS DE
RIGHT JOIN FUNCIONARIO AS F ON F.Cpf = DE.Fcpf
WHERE DE.Fcpf IS NULL;

SELECT *
FROM DEPARTAMENTO AS D
WHERE D.Dnumero NOT IN (SELECT DISTINCT F.DNR FROM FUNCIONARIO AS F WHERE F.Dnr IS NOT NULL );


SELECT *
FROM DEPARTAMENTO AS D
WHERE NOT EXISTS (SELECT 1 FROM FUNCIONARIO AS F WHERE F.Dnr = D.Dnumero);

SELECT * 
FROM FUNCIONARIO AS F
FULL JOIN DEPARTAMENTO AS D ON D.Dnumero = F.Dnr

SELECT F.Pnome 
FROM FUNCIONARIO AS F
UNION
SELECT DE.Nome_dependente
FROM DEPENDENTE AS DE

